name = "AxisymmLinStab"
uuid = "9892f48d-3b50-4d6f-91e2-d13b368ad736"
authors = ["Ian MacPherson"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
